/* Returns XP */
native get_user_xp(id)

/* Set XP */
native set_user_xp(id, points)

/* Returns XP for next Level */
native get_user_next_level_xp(id)


/* Returns Level */
native get_user_level(id)

/* Returns Max Level */
native get_max_level()


/* Returns ultimate */
native get_user_ultimate(id)

/* Returns Ultimate */
native get_user_ultimate_name(id)

/* Set Ultimate */
native set_user_ultimate(id, ultimate)